# Generated by Django 3.0.3 on 2020-02-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IKEAapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='img',
        ),
        migrations.AddField(
            model_name='commodity',
            name='img',
            field=models.ManyToManyField(to='IKEAapp.Ads', verbose_name='商品图片'),
        ),
    ]
