# Generated by Django 3.0.3 on 2020-02-17 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('creation_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'ordering': ['creation_time'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='选项名称')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='票数')),
                ('creation_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='polls.Issue', verbose_name='所选问题')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'ordering': ['creation_time'],
            },
        ),
    ]
