# Generated by Django 3.0.3 on 2020-02-16 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('option1_votes', models.IntegerField(default=0, verbose_name='选项1票数')),
                ('option2_votes', models.IntegerField(default=0, verbose_name='选项2票数')),
                ('option3_votes', models.IntegerField(blank=True, null=True, verbose_name='选项3票数')),
                ('option4_votes', models.IntegerField(blank=True, null=True, verbose_name='选项4票数')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(default='是', max_length=20, unique=True)),
                ('option2', models.CharField(default='不是', max_length=20, unique=True)),
                ('option3', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('option4', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='polls.Issue')),
            ],
        ),
    ]
