# Generated by Django 3.0.3 on 2020-02-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='option3_votes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='选项3票数'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='option4_votes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='选项4票数'),
        ),
    ]
