# Generated by Django 3.0.3 on 2020-02-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_account_concact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('summary', models.TextField(verbose_name='文章正文')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=10, verbose_name='标签名')),
                ('articles', models.ManyToManyField(related_name='tags', to='booktest.Article', verbose_name='文章')),
            ],
        ),
    ]
