# Generated by Django 3.0.4 on 2020-03-09 08:37

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
                ('img', models.ImageField(upload_to='category_ads', verbose_name='分类图片')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator', models.CharField(max_length=20, verbose_name='评论人')),
                ('img', DjangoUeditor.models.UEditorField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
                ('headImg', models.ImageField(upload_to='head/', verbose_name='头像')),
                ('sex', models.CharField(choices=[('女', 'Female'), ('男', 'Male')], max_length=1, verbose_name='性别')),
                ('berthday', models.DateField(blank=True, null=True, verbose_name='生日')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='鲜花名字')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='价格')),
                ('sales', models.FloatField(default=1.1, max_length=20, verbose_name='销量')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('materials', models.CharField(max_length=30, verbose_name='材料')),
                ('img', models.ImageField(upload_to='ads', verbose_name='图片')),
                ('distribution', models.CharField(default='全国', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_net.Category', verbose_name='分类名')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_net.Comment', verbose_name='评论')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_net.Tag', verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_net.FlowerGoods', verbose_name='商品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flower_net.User', verbose_name='用户')),
            ],
        ),
    ]
