# Generated by Django 3.0.4 on 2020-03-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='flower_net.FlowerGoods', verbose_name='商品 '),
        ),
    ]
